"use client";

import Link from "next/link";
import { ArrowLeft, ShieldCheck, Lock, CheckCircle2 } from "lucide-react";
import { soundFX } from "@/lib/audio";

export default function PrivacyPage() {
  return (
    <div className="min-h-screen bg-[#050507] text-white selection:bg-[#ccff00] selection:text-black">
      {/* Top Navigation */}
      <nav className="sticky top-0 z-50 backdrop-blur-xl bg-[#050507]/80 border-b border-white/10 px-4 sm:px-8 py-4">
        <div className="max-w-5xl mx-auto flex items-center justify-between">
          <Link
            href="/"
            onClick={() => soundFX.playClick()}
            className="inline-flex items-center gap-2 text-xs font-mono text-zinc-400 hover:text-[#ccff00] transition-colors"
          >
            <ArrowLeft className="w-4 h-4" />
            <span>BACK TO HOME</span>
          </Link>
          <div className="font-[family-name:var(--font-orbitron)] font-bold text-sm tracking-wider">
            CODE<span className="text-[#ccff00]">MEET</span> 2026
          </div>
        </div>
      </nav>

      {/* Main Content */}
      <main className="max-w-4xl mx-auto px-4 sm:px-6 py-12 sm:py-16 space-y-10">
        <div className="space-y-3 text-center sm:text-left border-b border-white/10 pb-8">
          <div className="inline-flex items-center gap-2 px-3 py-1 rounded-full bg-cyan-500/10 border border-cyan-500/30 text-cyan-400 text-xs font-mono font-bold">
            <ShieldCheck className="w-3.5 h-3.5" />
            <span>DATA PRIVACY &amp; SECURITY</span>
          </div>
          <h1 className="font-[family-name:var(--font-orbitron)] font-black text-3xl sm:text-4xl text-white">
            Privacy Policy
          </h1>
          <p className="text-zinc-400 font-mono text-xs sm:text-sm">
            Effective Date: October 2026 • Srinivas University Institute of Engineering &amp; Technology (SUIET)
          </p>
        </div>

        <div className="space-y-8 text-zinc-300 font-mono text-xs sm:text-sm leading-relaxed">
          {/* Section 1 */}
          <section className="space-y-3 p-6 rounded-2xl bg-zinc-950/80 border border-white/10">
            <h2 className="font-[family-name:var(--font-orbitron)] text-lg text-white font-bold flex items-center gap-2">
              <span className="text-cyan-400">01.</span> Information We Collect
            </h2>
            <p>
              When participants register for events and technical symposium workshops at CODEMEET 2026, we collect essential contact and academic details including:
            </p>
            <ul className="list-disc list-inside space-y-1.5 text-zinc-400">
              <li>Full Name and College/University affiliation</li>
              <li>Official Email Address and 10-digit Mobile Phone Number</li>
              <li>Team Name and Member Lineup details</li>
              <li>Transaction reference IDs generated by payment aggregators (no sensitive card/banking details are stored on our servers)</li>
            </ul>
          </section>

          {/* Section 2 */}
          <section className="space-y-3 p-6 rounded-2xl bg-zinc-950/80 border border-white/10">
            <h2 className="font-[family-name:var(--font-orbitron)] text-lg text-white font-bold flex items-center gap-2">
              <span className="text-cyan-400">02.</span> How We Use Your Data
            </h2>
            <p>
              Your personal information is strictly used for official event management purposes:
            </p>
            <ul className="list-disc list-inside space-y-1.5 text-zinc-400">
              <li>Issuing authentic Digital Entry IDs and registration passes</li>
              <li>Sending automated registration confirmation emails and event scheduling updates</li>
              <li>Facilitating on-campus venue verification and security check-in at SUIET Mukka</li>
              <li>Publishing official team certificates and academic merit acknowledgments</li>
            </ul>
          </section>

          {/* Section 3 */}
          <section className="space-y-3 p-6 rounded-2xl bg-zinc-950/80 border border-white/10">
            <h2 className="font-[family-name:var(--font-orbitron)] text-lg text-white font-bold flex items-center gap-2">
              <span className="text-cyan-400">03.</span> Payment Gateway Security
            </h2>
            <p>
              All financial transactions are handled directly through <strong>Razorpay</strong>, an RBI-authorized Payment Aggregator with 256-bit SSL encryption and PCI-DSS Level 1 certification. CODEMEET 2026 does not capture, process, or store credit/debit card numbers, CVVs, or UPI PINs.
            </p>
          </section>

          {/* Section 4 */}
          <section className="space-y-3 p-6 rounded-2xl bg-zinc-950/80 border border-white/10">
            <h2 className="font-[family-name:var(--font-orbitron)] text-lg text-white font-bold flex items-center gap-2">
              <span className="text-cyan-400">04.</span> Data Sharing &amp; Third Parties
            </h2>
            <p>
              We do not sell, rent, or trade participant data to commercial marketing third parties. Data is accessible solely to authorized SUIET faculty coordinators and event administrators for event execution.
            </p>
          </section>

          {/* Section 5 */}
          <section className="space-y-3 p-6 rounded-2xl bg-zinc-950/80 border border-white/10">
            <h2 className="font-[family-name:var(--font-orbitron)] text-lg text-white font-bold flex items-center gap-2">
              <span className="text-cyan-400">05.</span> Contacting Our Privacy Officer
            </h2>
            <p>
              For data access requests, corrections, or inquiries regarding your stored information, please email us at{" "}
              <a href="mailto:webflowcommunity@srinivasuniversity.edu.in" className="text-cyan-400 underline">
                webflowcommunity@srinivasuniversity.edu.in
              </a>.
            </p>
          </section>
        </div>

        {/* Navigation Footer */}
        <div className="pt-6 border-t border-white/10 flex flex-wrap items-center justify-between gap-4 text-xs font-mono text-zinc-500">
          <div>© 2026 Srinivas University (SUIET) • CODEMEET</div>
          <div className="flex items-center gap-4">
            <Link href="/terms" className="hover:text-[#ccff00] transition-colors">Terms of Service</Link>
            <Link href="/refund-policy" className="hover:text-[#ccff00] transition-colors">Refund Policy</Link>
            <Link href="/contact" className="hover:text-[#ccff00] transition-colors">Contact Us</Link>
          </div>
        </div>
      </main>
    </div>
  );
}
